services:
  portfolio:
    container_name: portfolio
    build:
      context: https://github.com/Hugo-CASTELL/pf.git
    restart: unless-stopped
    networks:
      - optiplex-net

networks:
  optiplex-net:
    external: true
